version: '3.1'

services:

  db:
    image: postgres
    container_name: snippetbox-db
    restart: always
    environment:
      POSTGRES_USER: web
      POSTGRES_PASSWORD: example
      POSTGRES_DB: snippetbox
    ports:
      - "5432:5432"