version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql-test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snippetbox
    ports:
      - "3306:3306"